apiVersion: v1
kind: Service
metadata:
  name: {{ include "forward.fullname" . }}
  labels:
    {{- include "forward.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
