apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mealie.fullname" . }}
  labels:
    {{- include "mealie.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mealie.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mealie.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mealie.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            {{- with (first .Values.ingress.hosts) }}
            - name: BASE_URL
              value: {{ .host }}
            {{- end }}
            - name: DB_ENGINE
              value: postgres
            - name: PGID
              value: "1000"
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: POSTGRES_SERVER
              value: {{ include "mealie.fullname" . }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            {{- with .Values.mealie.smtp.host }}
            - name: SMTP_HOST
              value: {{ . }}
            {{- end }}
            {{- with .Values.mealie.smtp.port }}
            - name: SMTP_PORT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.mealie.smtp.fromName }}
            - name: SMTP_FROM_NAME
              value: {{ . }}
            {{- end }}
            {{- with .Values.mealie.smtp.fromEmail }}
            - name: SMTP_FROM_EMAIL
              value: {{ . }}
            {{- end }}
            {{- with .Values.mealie.smtp.auth.strategy }}
            - name: SMTP_AUTH_STRATEGY
              value: {{ . }}
            {{- end }}
            {{- with .Values.mealie.smtp.auth.user }}
            - name: SMTP_USER
              value: {{ . }}
            {{- end }}
            {{- with .Values.mealie.smtp.auth.password }}
            - name: SMTP_PASSWORD
              value: {{ . }}
            {{- end }}
            - name: PUID
              value: "1000"
            {{- with .Values.mealie.tz }}
            - name: TZ
              value: {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: {{ .Values.mealie.persistenc.name }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
