apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .Values.mealie.persistence.name }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.mealie.persistence.size }}

