apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "forward.fullname" . }}
  labels:
    {{- include "forward.labels" . | nindent 4 }}
subsets:
  - addresses:
    {{- range $index, $address := .Values.addresses }}
    {{- range $key, $value := $address }}
      - {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }} 

